### PR TITLE
Dehumidifier untested

### PR DESCRIPTION
**Pull request by sittisal**
Added initial dehumidifier support, on top of development branch
Fixed few typescript issues recommended by VSCode
Couldn't test regression on AC because I have no AC
Tested with Inventor EVA II PRO WiFi (should be same as Midea)

### CODE REVIEW

**Comment by CyberMrProper** [comment]
I’ve just bought Inventor EVA II Pro WiFi, hope this PR gets merged soon so I can test it.

**Comment by ttimpe** [comment]
> I’ve just bought Inventor EVA II Pro WiFi, hope this PR gets merged soon so I can test it.

Enjoy

**Comment by CyberMrProper** [comment]
Great, will it be released under beta tag?

**Comment by CyberMrProper** [comment]
@sittisal I'm testing this in developing branch and is working great, thanks! 
Are you planning to add fan speed selector?

**Pull request merged**
